# Site settings
name: Sudheer Patil
title: Sudheer Patil | Android developer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://sudheerpatil.github.io/
baseurl: ''
email: patilsudheer1991@gmail.com
logo: https://sudheerpatil.github.io/img/emojis/technologist.png
resume: https://sudheerpatil.github.io/resume.pdf
social:
  - title: email
    url: mailto:patilsudheer1991@gmail.com
  - title: twitter
    url: https://x.com/patilsudheer91
  - title: github
    url: https://github.com/sudheerpatil
  - title: linkedin
    url: https://www.linkedin.com/in/sudheer-patil-65260864/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
